services:
  mongodb:
    image: mongo:latest
    container_name: smart_home_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    restart: unless-stopped

volumes:
  mongo_data:
